"""NOVELTY ENGINE — generate NEW mechanism packets from forced-flow templates (not variations of dead families).
Each packet: source-template, mechanism, forced participant, instrument, horizon, data, availability, PIT risk, harness,
kill criteria, priority. Writes docs/fql_forge/NOVELTY_PACKETS_<date>.md + feasible ones -> queue. Run: python3 research/forge_novelty_engine.py"""
import json
from pathlib import Path
from datetime import date
REPO=Path("/Users/chasefisher/projects/Algo Trading/algo-lab")
# template = (mechanism, forced-participant/why-price-insensitive, instrument, horizon, data, availability, harness, priority)
PACKETS=[
 ("Index reconstitution forced buy","index funds must buy adds at close on rebal date","MES/MNQ","rebal day","rebalance calendar + futures","DATA_BLOCKED (calendar)","event-adapter","MED"),
 ("Quad-witch OPEX gamma pin","dealers hedge short-gamma into expiry, pinning to max-OI strike","MES","OPEX week","ES options OI (GEX)","FEASIBLE (gamma pull)","gamma-regime","HIGH"),
 ("Month-end pension duration extension","bond index funds extend duration last session","ZN/ZB","last 1-3 sessions","futures + calendar","LOCAL (have)","calendar-adapter","MED"),
 ("Treasury auction concession/reversal","dealers demand concession pre-auction, unwind after","ZN/ZB","T-2..T+2","auction dates","LOCAL (treasury_auctions.csv)","wp_b1 (RAN=KILL)","DONE"),
 ("Settlement/cash-close reversion","large players mark on cash close, revert after","ZN/ZF","15:00-16:00 ET","1m futures","LOCAL (1m)","event-path-1m","MED-HIGH"),
 ("Futures roll-window pressure","longs must roll front->back over roll window","ZN/CL/MGC","roll window","per-contract","LOCAL (pulled per-contract)","term-structure","MED"),
 ("Commodity inventory-carry (EIA)","refiners/producers hedge post-inventory-surprise","CL","event day","EIA stocks + consensus","DATA_BLOCKED_CERT (EIA free API)","event-adapter","MED"),
 ("VIX-expiry VRO settlement flow","known settlement flow on VX expiry Wed","VX","expiry day","VX futures","DATABENTO_REPULL_CHECK (VX dataset)","event-adapter","MED"),
 ("Post-FOMC vol crush","hedges unwind, IV collapses after decision","MES/VX","FOMC day+1","options IV / vol","gamma-adjacent (feasible)","event-adapter","MED"),
 ("FX benchmark-fix (WMR 16:00) flow","benchmark-tracking funds transact at the fix","6E/6J/6B","fix window","1m FX","LOCAL (1m)","event-path-1m","MED"),
 ("Opening-auction imbalance resolution","overnight imbalance clears at cash open","MES/MNQ","first 30m","1m","LOCAL (1m)","intraday-path","LOW-MED (opening-drive KILLed once; re-spec on imbalance not drive)"),
 ("Crowded-positioning unwind (COT extreme + price break)","trapped specs forced to cut on adverse break","MGC/CL/6E","weekly","COT + futures","LOCAL (cot.csv)","cot-conditional (not naive fade)","MED"),
 ("Commodity contango roll-decay short","long-ETF holders bleed roll in steep contango","CL/NG","daily","per-contract curve","LOCAL (pulled)","term-structure-carry","MED-HIGH"),
 ("Cross-tenor duration RV (2s10s momentum)","macro funds trade curve slope; slow to reprice","ZN vs ZT","daily","per-contract","LOCAL (pulled)","curve-RV (fly KILLed; slope untested)","MED"),
 ("Post-holiday liquidity-return drift","desks re-risk after holiday illiquidity","MES","post-holiday","1m + calendar","LOCAL","calendar-adapter","LOW"),
]
lines=[f"# Novelty Packets — {date.today()}\n","> Generated by forge_novelty_engine.py. Each = forced-flow mechanism packet. Feasible ones queued.\n",
       "| # | mechanism | forced participant / why price-insensitive | instrument | horizon | data | availability | harness | priority |","|---|---|---|---|---|---|---|---|---|"]
for i,(m,p,inst,h,d,av,harn,pri) in enumerate(PACKETS,1):
    lines.append(f"| {i} | {m} | {p} | {inst} | {h} | {d} | {av} | {harn} | {pri} |")
feasible=[(m,harn) for (m,p,inst,h,d,av,harn,pri) in PACKETS if av.startswith("LOCAL") and "DONE" not in pri and "KILL" not in harn]
lines.append(f"\n**Generated {len(PACKETS)} packets. LOCAL-data feasible (queue-ready): {len(feasible)}.** Quota target: 10 source + 5 official + 5 rescue/day.")
(REPO/f"docs/fql_forge/NOVELTY_PACKETS_{date.today()}.md").write_text("\n".join(lines))
print(f"generated {len(PACKETS)} novelty packets; {len(feasible)} LOCAL-feasible")
for m,h in feasible[:8]: print(f"  feasible: {m} [{h}]")
