"""Signal and Equity Logger for Paper Trading.

Logs every signal, regime state, controller decision, and daily equity
during paper trading. Produces the daily JSON logs required by
PHASE_7_PAPER_TRADING_PLAN.md.
"""

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional


LOG_DIR = Path(__file__).resolve().parent.parent / "research" / "paper_trade_sim" / "daily_logs"


@dataclass
class SignalEvent:
    """A single signal generated by a strategy."""
    strategy: str
    time: str
    direction: str        # "long" or "short"
    stop_price: float
    target_price: float
    action: str           # "taken", "skipped_regime", "skipped_prop", "skipped_position"


@dataclass
class TradeEvent:
    """A completed trade."""
    strategy: str
    entry_time: str
    entry_price: float
    exit_time: str
    exit_price: float
    direction: str
    pnl: float
    exit_reason: str      # "stop", "target", "eod_flatten", "signal_reversal"


@dataclass
class ControllerState:
    """Prop controller state at end of day."""
    equity: float
    trailing_floor: float
    phase: str
    daily_pnl: float
    cumulative_pnl: float


@dataclass
class DailyLog:
    """Complete daily log entry for paper trading."""
    date: str
    regime: dict = field(default_factory=dict)
    signals: list = field(default_factory=list)
    trades: list = field(default_factory=list)
    controller: dict = field(default_factory=dict)
    notes: str = ""


class PaperTradeLogger:
    """Manages daily logging for paper trading sessions."""

    def __init__(self, log_dir: Optional[Path] = None):
        self.log_dir = log_dir or LOG_DIR
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self._current_date: Optional[str] = None
        self._current_log: Optional[DailyLog] = None

    def start_day(self, date: str, regime: dict):
        """Initialize logging for a new trading day.

        Args:
            date: ISO date string (YYYY-MM-DD)
            regime: Dict with atr_pctrank, label, gate decision
        """
        self._current_date = date
        self._current_log = DailyLog(
            date=date,
            regime=regime,
        )

    def log_signal(self, signal: SignalEvent):
        """Record a signal event."""
        if self._current_log is None:
            return
        self._current_log.signals.append(asdict(signal))

    def log_trade(self, trade: TradeEvent):
        """Record a completed trade."""
        if self._current_log is None:
            return
        self._current_log.trades.append(asdict(trade))

    def log_controller_state(self, state: ControllerState):
        """Record end-of-day controller state."""
        if self._current_log is None:
            return
        self._current_log.controller = asdict(state)

    def add_note(self, note: str):
        """Add an operational note for the day."""
        if self._current_log is None:
            return
        if self._current_log.notes:
            self._current_log.notes += "; "
        self._current_log.notes += note

    def end_day(self) -> Path:
        """Finalize and save the daily log.

        Returns path to the saved log file.
        """
        if self._current_log is None:
            raise RuntimeError("No active day to end. Call start_day() first.")

        log_path = self.log_dir / f"{self._current_date}.json"
        with open(log_path, "w") as f:
            json.dump(asdict(self._current_log), f, indent=2)

        saved_path = log_path
        self._current_log = None
        self._current_date = None
        return saved_path

    def load_day(self, date: str) -> Optional[dict]:
        """Load a previously saved daily log."""
        log_path = self.log_dir / f"{date}.json"
        if log_path.exists():
            with open(log_path) as f:
                return json.load(f)
        return None

    def get_all_logs(self) -> list[dict]:
        """Load all daily logs, sorted by date."""
        logs = []
        for p in sorted(self.log_dir.glob("*.json")):
            with open(p) as f:
                logs.append(json.load(f))
        return logs

    def summary(self) -> dict:
        """Compute summary statistics across all logged days."""
        logs = self.get_all_logs()
        if not logs:
            return {"days": 0}

        total_trades = sum(len(log.get("trades", [])) for log in logs)
        total_signals = sum(len(log.get("signals", [])) for log in logs)
        trade_pnls = [
            t["pnl"]
            for log in logs
            for t in log.get("trades", [])
        ]

        skipped_days = sum(
            1 for log in logs
            if log.get("regime", {}).get("gate") == "skip"
        )

        return {
            "days": len(logs),
            "trading_days": len(logs) - skipped_days,
            "skipped_days": skipped_days,
            "total_signals": total_signals,
            "total_trades": total_trades,
            "total_pnl": sum(trade_pnls) if trade_pnls else 0,
            "win_rate": (
                sum(1 for p in trade_pnls if p > 0) / len(trade_pnls)
                if trade_pnls else 0
            ),
            "avg_trade_pnl": (
                sum(trade_pnls) / len(trade_pnls)
                if trade_pnls else 0
            ),
        }
